spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project1_db
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
        ddl-auto: none
    show-sql: true
  #jackson:
    #date-format: yyyy-MM-dd HH:mm:ss
    #time-zone: GMT+8
  


#redis setting
#spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 60000

#port
server.port: 8083