server.port: 8086


#https://www.coingecko.com/en/api/documentation
API:
  Crypto:
    baseUrl: https://api.polygon.io
    serviceVers: v2
    serviceUrl: 
      previous_close: 
        path1: aggs/ticker
        path3: prev
        parm:
          ajusted: true
  api_key: I8MqMDt5c_mXOuAMdWJEP_Kkb8XGi9au
