server.port: 8086


API:
  Crypto:
    baseUrl: https://api.polygon.io
    serviceVers: v2
    serviceUrl: 
      previous_close: 
        path1: aggs/ticker
        path3: prev
        parm:
          ajusted: true
  api_key: #not gonna provide
